// Generate a minimum-viable smoke test per live content page.
//
// Each test file asserts two things:
//   1. renders_title — the page's hero title is visible by its English copy
//   2. nav_back_home — clicking the page's breadcrumb (or the site brand
//      mark) navigates to `/`
//
// Test files are authored as JSON under tests/screens/<path>.test.json.
// The runner (`jsonui-test`) discovers them automatically. Pages that
// already have a hand-authored test file are skipped so richer per-page
// test suites (home, hello-world, installation) are preserved.
//
// Source of truth: public/search-index.json for URL + title.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

interface IndexEntry {
  url: string;
  title: { en: string; ja: string };
  namespace: string;
}
interface SearchIndex {
  version: number;
  entries: IndexEntry[];
}

const PROJECT_ROOT = resolve(__dirname, "..", "..");
const indexPath = resolve(__dirname, "..", "public", "search-index.json");
const testsRoot = join(PROJECT_ROOT, "tests", "screens");

const idx: SearchIndex = JSON.parse(readFileSync(indexPath, "utf8"));

let written = 0;
let skipped = 0;

for (const entry of idx.entries) {
  // URL → tests/screens/<path>.test.json. Strip leading slash, append extension.
  const rel = entry.url.replace(/^\//, "") + ".test.json";
  const out = join(testsRoot, rel);

  if (existsSync(out)) {
    skipped++;
    continue;
  }

  // Derive the screen identifier the test runner expects — same as the
  // page URL without the leading slash. Matches the convention used by
  // the existing home.test.json / learn/hello-world.test.json files.
  const screenPath = entry.url.replace(/^\//, "");

  const file = {
    $schema: "../../jsonui-test.schema.json",
    screen: screenPath,
    description: `Smoke test: ${entry.title.en}. Generated by scripts/gen-smoke-tests.ts.`,
    cases: [
      {
        name: "renders_title",
        description: `Page mounts and shows the hero title.`,
        steps: [
          {
            assert: "contains",
            root: true,
            text: entry.title.en,
          },
        ],
      },
      {
        name: "nav_back_home",
        description: "Tapping the site brand (top-left) returns to home.",
        steps: [
          {
            interact: "tap",
            role: "link",
            text: "JsonUI",
          },
          {
            assert: "url",
            equals: "/",
          },
        ],
      },
    ],
  };

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify(file, null, 2) + "\n");
  written++;
}

console.log(
  `gen-smoke-tests: wrote ${written} new test files, skipped ${skipped} existing`,
);
