// Generate a minimum-viable smoke test per live content page.
//
// Each test file asserts one thing: the page mounts and its root element
// is visible. The root id follows the layout convention `<namespace>_root`,
// which the search index already carries, so the assertion survives copy
// changes — an earlier version matched the hero's English text and the
// site brand by role, neither of which the runner's step vocabulary has.
//
// Test files are authored as JSON under tests/screens/<path>.test.json.
// The runner (`jsonui-test`) discovers them automatically. Pages that
// already have a hand-authored test file are skipped so richer per-page
// test suites (home, hello-world, installation) are preserved.
//
// Source of truth: public/search-index.json for URL + title.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

interface IndexEntry {
  url: string;
  title: { en: string; ja: string };
  namespace: string;
}
interface SearchIndex {
  version: number;
  entries: IndexEntry[];
}

const PROJECT_ROOT = resolve(__dirname, "..", "..");
const indexPath = resolve(__dirname, "..", "public", "search-index.json");
const testsRoot = join(PROJECT_ROOT, "tests", "screens");

const idx: SearchIndex = JSON.parse(readFileSync(indexPath, "utf8"));

let written = 0;
let skipped = 0;

for (const entry of idx.entries) {
  // URL → tests/screens/<path>.test.json. Strip leading slash, append extension.
  const rel = entry.url.replace(/^\//, "") + ".test.json";
  const out = join(testsRoot, rel);

  if (existsSync(out)) {
    skipped++;
    continue;
  }

  // Derive the screen identifier the test runner expects — same as the
  // page URL without the leading slash. Matches the convention used by
  // the existing home.test.json / learn/hello-world.test.json files.
  const screenPath = entry.url.replace(/^\//, "");

  // Shape follows the runner's screen-test schema (type / metadata /
  // platform / cases). An earlier version of this script emitted a
  // hand-rolled shape with a top-level `screen` and no `type`, which the
  // validator rejects — those files were collected and skipped rather
  // than run, so the pages they should have produced never appeared.
  const file = {
    type: "screen",
    metadata: {
      name: entry.title.en,
      description: `Smoke test: ${entry.title.en}. Generated by scripts/gen-smoke-tests.ts.`,
      generatedBy: "scripts/gen-smoke-tests.ts",
      tags: ["smoke", "web"],
      screen: screenPath,
    },
    platform: "web",
    cases: [
      {
        name: "renders",
        description: `The page mounts and its root is visible.`,
        steps: [
          { action: "waitFor", id: `${entry.namespace}_root`, timeout: 5000 },
          { assert: "visible", id: `${entry.namespace}_root` },
        ],
      },
    ],
  };

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify(file, null, 2) + "\n");
  written++;
}

console.log(
  `gen-smoke-tests: wrote ${written} new test files, skipped ${skipped} existing`,
);
