// LanguageSelector.tsx
// Language selection dropdown for multi-language support
// Generated by: rjui g converter LanguageSelector

"use client";

import React, { useState, useEffect } from 'react';
import StringManager from '@/generated/StringManager';

interface LanguageSelectorProps {
  children?: React.ReactNode;
  className?: string;
}

const languageLabels: Record<string, string> = {
  en: 'English',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
};

export const LanguageSelector: React.FC<LanguageSelectorProps> = ({ className }) => {
  const [currentLang, setCurrentLang] = useState('en');
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    const savedLang = localStorage.getItem('jsonui-language');
    if (savedLang && StringManager.availableLanguages.includes(savedLang)) {
      setCurrentLang(savedLang);
      StringManager.setLanguage(savedLang);
    } else {
      const browserLang = navigator.language.split('-')[0];
      if (StringManager.availableLanguages.includes(browserLang)) {
        setCurrentLang(browserLang);
        StringManager.setLanguage(browserLang);
      }
    }
  }, []);

  const handleLanguageChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const newLang = event.target.value;
    setCurrentLang(newLang);
    StringManager.setLanguage(newLang);
    localStorage.setItem('jsonui-language', newLang);
    window.location.reload();
  };

  const availableOptions = StringManager.availableLanguages.map((code: string) => ({
    code,
    label: languageLabels[code] || code.toUpperCase(),
  }));

  if (!isClient) {
    return null;
  }

  return (
    <select
      value={currentLang}
      onChange={handleLanguageChange}
      className={`
        border border-gray-300 rounded-md px-2 py-1
        bg-white text-gray-700 text-sm
        cursor-pointer outline-none
        focus:ring-2 focus:ring-blue-500 focus:border-blue-500
        ${className || ''}
      `}
    >
      {availableOptions.map((option) => (
        <option key={option.code} value={option.code}>
          {option.label}
        </option>
      ))}
    </select>
  );
};

export default LanguageSelector;
