// LanguageProvider.tsx
// Initializes language from localStorage before rendering children
// Generated by: rjui g converter LanguageProvider

"use client";

import React, { useState, useEffect } from 'react';
import StringManager from '@/generated/StringManager';

interface LanguageProviderProps {
  children?: React.ReactNode;
  className?: string;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children, className }) => {
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem('jsonui-language');
    if (savedLang && StringManager.availableLanguages.includes(savedLang)) {
      StringManager.setLanguage(savedLang);
    } else {
      const browserLang = navigator.language.split('-')[0];
      if (StringManager.availableLanguages.includes(browserLang)) {
        StringManager.setLanguage(browserLang);
        localStorage.setItem('jsonui-language', browserLang);
      }
    }
    setIsInitialized(true);
  }, []);

  if (!isInitialized) {
    return null;
  }

  return <>{children}</>;
};

export default LanguageProvider;
