# frozen_string_literal: true

# Generated by: rjui g converter CodeBlock --attributes file:String,language:String,showPreview:Boolean

require_relative '../base_converter'

module RjuiTools
  module React
    module Converters
      module Extensions
        class CodeBlockConverter < BaseConverter
          def convert(indent = 2)
            class_name = build_class_name
            id_attr = extract_id ? %( id="#{extract_id}") : ''

            file_value = json['file']
            language_value = json['language']
            showPreview_value = json['showPreview']

            # Build the component JSX
            props = []
            props << %(file="#{file_value}") if file_value
            props << %(language="#{language_value}") if language_value
            props << "showPreview={#{showPreview_value}}" unless showPreview_value.nil?
            props_str = props.empty? ? '' : " #{props.join(' ')}"

            <<~JSX.chomp
              #{indent_str(indent)}<CodeBlock#{id_attr} className="#{class_name}"#{props_str} />
            JSX
          end

          protected

          def build_class_name
            classes = ['flex', 'flex-col']

            classes << TailwindMapper.map_width(json['width']) if json['width']
            classes << TailwindMapper.map_flex_grow(json['weight']) if json['weight']

            classes.compact.reject(&:empty?).join(' ')
          end
        end
      end
    end
  end
end
