# frozen_string_literal: true

# This file maps custom component types to their converter classes
# Auto-generated by rjui g converter command

module RjuiTools
  module React
    module Converters
      module Extensions
        CONVERTER_MAPPINGS = {
          'CodeBlock' => 'CodeBlockConverter',
        }.freeze
      end
    end
  end
end
