# frozen_string_literal: true

# Generated by: rjui g converter DocSamplePreview

require_relative '../base_converter'

module RjuiTools
  module React
    module Converters
      module Extensions
        class DocSamplePreviewConverter < BaseConverter
          def convert(indent = 2)
            class_name = build_class_name
            id_attr = extract_id ? %( id="#{extract_id}") : ''

            # No custom attributes

            # Build the component JSX
            props = []
            # No custom props
            props_str = props.empty? ? '' : " #{props.join(' ')}"

            # Auto-detect container based on children or child
            is_container = (json['children'] && !json['children'].empty?) || (json['child'] && !json['child'].empty?)

            if is_container
              children_jsx = convert_children(indent + 2)
              <<~JSX.chomp
                #{indent_str(indent)}<DocSamplePreview#{id_attr} className="#{class_name}"#{props_str}>
                #{children_jsx}
                #{indent_str(indent)}</DocSamplePreview>
              JSX
            else
              <<~JSX.chomp
                #{indent_str(indent)}<DocSamplePreview#{id_attr} className="#{class_name}"#{props_str} />
              JSX
            end
          end

          protected

          def build_class_name
            # Get base classes from parent (handles margins, padding, etc.)
            base_classes = super

            # Add component-specific classes
            classes = ['flex', 'flex-col']
            classes << base_classes unless base_classes.empty?

            classes.compact.reject(&:empty?).join(' ')
          end
        end
      end
    end
  end
end
